services:
  web:
    build: .
    ports:
      - "8082:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: proyecto-1-web
    depends_on:
      - backend

  backend:
    build: ./backend_react
    ports:
      - "8001:8000"
    environment:
      - NOTION_API_KEY=${NOTION_API_KEY}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - NOTION_HISTORY_DB_ID=${NOTION_HISTORY_DB_ID}
      - NOTION_CLIENTS_DB_ID=${NOTION_CLIENTS_DB_ID}
      - NOTION_CLIENTS_HISTORY_DB_ID=${NOTION_CLIENTS_HISTORY_DB_ID}
      - NOTION_SUPPORT_DB_ID=${NOTION_SUPPORT_DB_ID}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    container_name: proyecto-1-backend-react
